name: rapidserve
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^10.3.3
  flutter_riverpod: ^2.6.1
  image_picker: ^1.1.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  google_fonts: ^6.3.2
  fl_chart: ^1.1.0
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  google_maps_flutter: ^2.13.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo1.png"
  min_sdk_android: 21